controllers/AnimalController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Animal;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AnimalController implements the CRUD actions for Animal model.
 */
class AnimalController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Animal models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Animal::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Animal model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Animal model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Animal();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo_animal]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Animal model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo_animal]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Animal model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Animal model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Animal the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Animal::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    
}

controllers/ClienteController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Cliente;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ClienteController implements the CRUD actions for Cliente model.
 */
class ClienteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Cliente models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Cliente::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Cliente model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Cliente model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Cliente();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo_cliente]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Cliente model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo_cliente]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Cliente model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Cliente model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Cliente the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Cliente::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/NoticiaController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Noticia;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * NoticiaController implements the CRUD actions for Noticia model.
 */
class NoticiaController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Noticia models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Noticia::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Noticia model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Noticia model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Noticia();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->titulo]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Noticia model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->titulo]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Noticia model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Noticia model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Noticia the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Noticia::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Noticia;
use yii\data\ActiveDataProvider;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
     public function actionGuia()
    {
        return $this->render('guia');
    }
    
     public function actionQuienessomos()
    {
        return $this->render('quienessomos');
    }
    
      public function actionAdoptados()
    {
        return $this->render('adoptados');
    }
    
     public function actionMostrarnoticias(){
        $dataProvider = new ActiveDataProvider([  
         'query' => Noticia::find(),
     ]);
    
        return $this->render("todaslasnoticias",[
            
            "dataProvider"=>$dataProvider,
            
        ]);
    }
    
}

controllers/SocioController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Socio;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SocioController implements the CRUD actions for Socio model.
 */
class SocioController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Socio models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Socio::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Socio model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Socio model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Socio();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo_socio]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Socio model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->codigo_socio]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Socio model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Socio model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Socio the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Socio::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/site/_noticia.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\data\ActiveDataProvider;

$this->title = "Todas las noticias";

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>

<div class="col-md-4">
    <div class="thumbnail noticias" style="max-height: 900px;">
        <div class="caption" style="border-style: solid">
            
            <div style="margin:11px;" align="center">
                
                <h3><?= "". $model->titulo ?></h3>
                
            </div>
             
            <div style="margin:40px;" align="justify">
                <?= "". $model->cuerpo ?>
            </div>
                
                 
            <div align="center">
                <?= Html::img($model->imagen, ['alt' => 'My logo']) ?>
            </div>
            
        </div>
    </div>
</div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/adoptados.php
<?php

use yii\helpers\Html;

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


$this->title = 'Adoptados';
$this->params['breadcrumbs'][] = $this->title;

?>

<h1 style="color:#8E44AD"><b><i>Adoptados</i></b></h1>

<br>
        
<table>

    <tr>
        
        <td>

<div align="center" style="border:5px solid #00b3ee;" class="col-lg-12">
                       
               <h3><strong>Toby</strong></h3>
               
               <br>

               <p><?= Html::img('@web/images/perro_adoptado_ pagina_principal.jpg', ['alt' => 'Error al mostrar la imagen'])?></p>
               
               <br>
               
               <h3>Detalles del animal:</h3>
                   
               <br>
                   
                   <div align="center">
                       
                       <p><strong>Nombre: </strong>Toby</p>
                       <p><strong>Fecha de entrada: </strong>20/03/2020</p>
                       <p><strong>Fecha de salida: </strong>8/04/2020</p>
                       <p><strong>Lugar actual: </strong>Local calle Lamara</p>
                       <p><strong>Tipo: </strong>Perro</p>
                       <p><strong>Edad: </strong>4 años</p>
                       <p><strong>Sexo: </strong> Macho</p>
                       <p><strong>Tamaño: </strong> Mediano</p>
                       <p><strong>Raza: </strong> Labrador</p>
                       <p><strong>Vacunado: </strong> Si</p>
                       <p><strong>Esterilizado: </strong> Si</p>
                       
                   </div>
               
               <br>
               <br>
               
               <p>................................................................................................................................................</p>
               
               <br>
               
                   <h3 align="center">Descripción.</h3>
               
                   <p align="center"><strong>ADOPTADO</strong></p>
               
               <p align="justify">En la tarde de ayer, día ocho de abril, una chica de veintiún años y llamada Annabeth se presentó en nuestras instalaciones de la calle Lamara. Se mostró muy interesada por nuestro cachorro, y al cabo de un rato hablando con uno de nuestros empleados, se decantó por acoger al pequeño. Después de unos trámites nuestro querido amigo ya puede disfrutar de su nueva familia.</p>
               
               <br>
               
               </div>
    
        </td>

    </tr>

    <tr>
    
        <td>
               <br>            
               <br>
               
               
                <div align="center" style="border:5px solid #00b3ee;" class="col-lg-12">
                   
                <h3><strong>Simba</strong></h3>
                
                <br>
                    
                <p><?= Html::img('@web/images/jessy gatita adoptado.jpg', ['alt' => 'Error al mostrar la imagen'])?></p>
                   
                <br>
                
                   <h3 align="center">Detalles del animal:</h3>
                   
               <br>
                   
               <div align="center">
                   
                       <p><strong>Nombre: </strong>Simba</p>
                       <p><strong>Fecha de entrada: </strong>13/04/2020</p>
                       <p><strong>Fecha de salida: </strong>13/05/2020</p>
                       <p><strong>Lugar actual: </strong>Local calle Giralda</p>
                       <p><strong>Tipo: </strong>Gato</p>
                       <p><strong>Edad: </strong>2 años</p>
                       <p><strong>Sexo: </strong> Macho</p>
                       <p><strong>Tamaño: </strong> Pequeño</p>
                       <p><strong>Raza: </strong> común</p>
                       <p><strong>Vacunado: </strong> Si</p>
                       <p><strong>Esterilizado: </strong> Si</p>
                       
              </div>
               
               <br>
               <br>
               
               <p>................................................................................................................................................</p>
               
               <br>
                
                <h3 align="center">Descripción.</h3>
                
                <p align="center"><strong>ADOPTADO</strong></p>
                
                <p align="justify">Simba ha sido adoptado durante esta misma mañana al ser acogido por los padres de una familia numerosa, a la cual, les encantó el gatito nada más verle.</p> 
                
                <br>
                
                </div>
     
               </td>

        </tr>
               
</table>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */

$this->title = 'Protectora de animales Kinodraconelasa';

?>

<html>
    <head>
    
        <style>
            
            #table1 {
               border-collapse: separate;
               border-spacing: 50px;
            } 
            
        </style>
            
    </head>
    
    <body>

<nav>
    
    <div class="body-content">

                <div class="row" style="border-style: double">
        
                    <div align="center" border-style="double">
        
                             <div class="col-lg-4" style="background-color: pink">
                             <p></p>
                             <p><?= Html::a('¿Quiénes somos?', ['site/quienessomos'])?></p>
                             </div>
                            
                             <div class="col-lg-4" style="background-color: pink">
                             <p></p>
                             <p><?= Html::a('Adoptados', ['site/adoptados'])?></p>
                             </div>
                            
                            <div class="col-lg-4" style="background-color: pink">
                            <p></p>
                            <p><?= Html::a('Todas las noticias', ['site/mostrarnoticias'])?></p>
                            </div>
                            
                       </div>
        
               </div>
        
           </div>
    
</nav>

<table id="table1">
    
    <tr>
        
        <td>
    
            <div class="body-content" style="background-color: #A9CCE3">

        <div style="border-style: double">
                
     <br>
        
     <div class="col-lg-15">
     <p align="center"><?= Html::a('Consultar información de los animales', ['animal/index'], ['class' => 'btn btn-primary'])?></p>
    </div>
      <br>
      <div class="col-lg-15">
     <p align="center"><?= Html::a('Consultar información de los clientes', ['cliente/index'], ['class' => 'btn btn-primary'])?></p>
      </div>
      <br>
      <div class="col-lg-15">
     <p align="center"><?= Html::a('Consultar información de los empleados', ['empleado/index'], ['class' => 'btn btn-primary'])?></p>
      </div>
      <br>
      <div class="col-lg-15">
     <p align="center"><?= Html::a('Consultar información de los socios', ['socio/index'], ['class' => 'btn btn-primary'])?></p>
      </div> 
     <br>
      <div class="col-lg-15">
     <p align="center"><?= Html::a('Consultar noticias', ['noticia/index'], ['class' => 'btn btn-primary'])?></p>
      </div>
     <br>
      
            </div>
        
        </div>

        </td>
        
    
    <td>
             
             <div style="border-style: double; background-color: #ffe8a1;" class="col-lg-12">
                 
                 <div class="body-content" style="background-color: #ffe8a1">
                     
                     <br>
                     
            <div style="color:#0a73bb" align="justify">
                <h3><b><i>ÚLTIMAS NOTICIAS</i></b></h3>
            </div>
               
                <br>
                <h3 align="center" style="background-color: #ffe8a1">¡Toby ha sido adoptado!</h3>
                <br>
                <p align="center" style="background-color: #ffe8a1">En la tarde de ayer, día ocho de abril, una chica de veintiún años y llamada Annabeth se presentó en nuestras instalaciones de la calle Lamara.</p> <p align="center" style="background-color: #ffe8a1">Se mostró muy interesada por nuestro cachorro, y al cabo de un rato hablando con uno de nuestros empleados, se decantó por acoger al pequeño.</p> <p align="center" style="background-color: #ffe8a1">Después de unos trámites nuestro querido amigo ya puede disfrutar de su nueva familia.</p>
                <br>
                <p align="center" style="background-color: #ffe8a1"><img src="/ProtectoraAnimalesKinodraconelasaFinDeCiclo/web/images/perro_adoptado_ pagina_principal.jpg" alt="Error al mostrar la imagen"></p>
                
                <br>
                
            </div>
                
            </div>
                 
               
            
        </td>
    <br>
</tr>

<br>

<tr>
    
    <td>
        
         <div class="body-content">

        <div class="pull-right" style="border-style: double">
            
            <div class="col-lg-12" style="background-color: #D2B4DE">
                
 <div align="justify">
    
<br>

<h2 style="color:#8E44AD" align="left"><b><i>Secciones de interés</i></b></h2>
         
         <div style="color:#8E44AD">
             
             <br>
             
             <p style="color:#0a73bb"><?= Html::a('Guía de adopción, importante si quieres adoptar...', ['site/guia'], ['class' => 'btn btn-primary'] )?></p>

<br>

         </div>
            
</div>
 </div>
            </div>
        </div>
     
</td>
</tr>

<br>
<br>
    
</table>
        
    </body>
    
    </html>

views/site/todaslasnoticias.php
<?php

use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\widgets\ListView;

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$this->title = 'Todas las noticias';
$this->params['breadcrumbs'][] = $this->title;

?>
   
<h1 style="color:#8E44AD"><b><i>Todas las noticias</i></b></h1>

<br>

<p>
    <?=    Html::a('Crear noticia', ['noticia/create'], ['class' => 'btn btn-warning']) ?>
</p>

<br>

<div class="row">
<?=    ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_noticia',
            'layout'=>"{pager}\n{items}",
    
]);
?>
    
    
</div>